FROM node:12.22.9-buster-slim

# set the working directory in the container
RUN mkdir /app
RUN chmod 777 /app
WORKDIR /app

# add `/app/node_modules/.bin` to $PATH
# ENV PATH=/app/node_modules/.bin:$PATH
# ENV CHOKIDAR_USEPOLLING=true
# ENV NODE_ENV=dev
# ENV CHOKIDAR_USEPOLLING=true

COPY package.json yarn.lock .
RUN yarn install

COPY . .

CMD ["yarn", "start"]
